version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7

    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install Dependencies
          command: bundle install

      - run:
          name: Generate Site
          command: JEKYLL_ENV=production bundle exec jekyll build

  deploy:
    docker:
      - image: jamcswain/circleci-aws-cli

    steps:
      - checkout

      - run:
          name: Push to S3
          command: aws s3 sync _site/. s3://${ORIGIN_BUCKET_NAME}

      - run:
          name: Clear Cloudfront Cache
          command: aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
